[[services]]
name = "backend"
source = "."
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.prod"

[services.backend.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[services.backend.env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"

[[services]]
name = "frontend"
source = "frontend"
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.railway"

[services.frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300

[services.frontend.env]
NODE_ENV = "production"
VITE_API_URL = "https://itarent02back-production.up.railway.app" 