# Railway конфигурация для полного деплоя ITA_RENT_BOT
[[services]]
name = "backend"
source = "."
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.prod"

[services.backend.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[services.backend.env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"

[[services]]
name = "frontend"
source = "frontend"
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.railway"

[services.frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

# ENV переменные уже настроены в Dockerfile.railway

# Новый сервис для автоматического парсинга каждые 6 часов
[[services]]
name = "scraper-worker"
source = "."
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.scraper"

[services.scraper-worker.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[services.scraper-worker.env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
WORKER_TYPE = "scraper"

# Telegram бот сервис
[[services]]
name = "telegram-bot"
source = "."
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.prod"
build.buildCommand = "echo 'Telegram bot service'"

[services.telegram-bot.deploy]
startCommand = "python run_telegram_bot.py"
healthcheckPath = ""
healthcheckTimeout = 300
restartPolicyType = "always"

[services.telegram-bot.env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
SERVICE_TYPE = "telegram-bot"

# Диспетчер уведомлений (cron)
[[services]]
name = "notification-worker"
source = "."
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.prod"
build.buildCommand = "echo 'Notification worker service'"

[services.notification-worker.deploy]
startCommand = "while true; do python cron_notifications.py; sleep 1800; done"
healthcheckPath = ""
healthcheckTimeout = 300
restartPolicyType = "always"

[services.notification-worker.env]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
SERVICE_TYPE = "notification-worker"

# PostgreSQL база данных (создается автоматически в Railway)
# [[services]]
# name = "postgres"
# ... 