"""Add new filter fields: agency_commission, renovation_type, building_type, year_built, park_nearby, noisy_roads_nearby, children_friendly

Revision ID: 02c2447c7fa9
Revises: cb0998cc8a63
Create Date: 2025-11-04 20:38:18.936126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c2447c7fa9'
down_revision: Union[str, None] = 'cb0998cc8a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('agency_commission', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('children_friendly', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('renovation_type', sa.String(length=50), nullable=True))
    op.add_column('listings', sa.Column('building_type', sa.String(length=50), nullable=True))
    op.add_column('listings', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('park_nearby', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('noisy_roads_nearby', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_listings_agency_commission'), 'listings', ['agency_commission'], unique=False)
    op.create_index(op.f('ix_listings_building_type'), 'listings', ['building_type'], unique=False)
    op.create_index(op.f('ix_listings_children_friendly'), 'listings', ['children_friendly'], unique=False)
    op.create_index(op.f('ix_listings_noisy_roads_nearby'), 'listings', ['noisy_roads_nearby'], unique=False)
    op.create_index(op.f('ix_listings_park_nearby'), 'listings', ['park_nearby'], unique=False)
    op.create_index(op.f('ix_listings_renovation_type'), 'listings', ['renovation_type'], unique=False)
    op.create_index(op.f('ix_listings_year_built'), 'listings', ['year_built'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_year_built'), table_name='listings')
    op.drop_index(op.f('ix_listings_renovation_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_park_nearby'), table_name='listings')
    op.drop_index(op.f('ix_listings_noisy_roads_nearby'), table_name='listings')
    op.drop_index(op.f('ix_listings_children_friendly'), table_name='listings')
    op.drop_index(op.f('ix_listings_building_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_agency_commission'), table_name='listings')
    op.drop_column('listings', 'noisy_roads_nearby')
    op.drop_column('listings', 'park_nearby')
    op.drop_column('listings', 'year_built')
    op.drop_column('listings', 'building_type')
    op.drop_column('listings', 'renovation_type')
    op.drop_column('listings', 'children_friendly')
    op.drop_column('listings', 'agency_commission')
    # ### end Alembic commands ###
