"""add notification_email separate from login email

Revision ID: cb0998cc8a63
Revises: f91922fe679a
Create Date: 2025-10-28 21:23:05.166943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0998cc8a63'
down_revision: Union[str, None] = 'f91922fe679a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email_notifications_enabled'), 'users', ['email_notifications_enabled'], unique=False)
    op.create_index(op.f('ix_users_notification_email'), 'users', ['notification_email'], unique=False)
    op.create_index(op.f('ix_users_telegram_notifications_enabled'), 'users', ['telegram_notifications_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_notifications_enabled'), table_name='users')
    op.drop_index(op.f('ix_users_notification_email'), table_name='users')
    op.drop_index(op.f('ix_users_email_notifications_enabled'), table_name='users')
    op.drop_column('users', 'notification_email')
    # ### end Alembic commands ###
