"""Initial migration: create base tables

Revision ID: ce901f74c668
Revises: 
Create Date: 2025-07-23 13:23:32.490504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce901f74c668'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('virtual_tour_url', sa.String(length=1024), nullable=True),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_listing_city_price', 'listings', ['city', 'price'], unique=False)
    op.create_index('idx_listing_coordinates', 'listings', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_listing_rooms_area', 'listings', ['rooms', 'area'], unique=False)
    op.create_index('idx_listing_scraped_at', 'listings', ['scraped_at'], unique=False)
    op.create_index('idx_listing_source_active', 'listings', ['source', 'is_active'], unique=False)
    op.create_index(op.f('ix_listings_area'), 'listings', ['area'], unique=False)
    op.create_index(op.f('ix_listings_city'), 'listings', ['city'], unique=False)
    op.create_index(op.f('ix_listings_district'), 'listings', ['district'], unique=False)
    op.create_index(op.f('ix_listings_external_id'), 'listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_is_active'), 'listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_listings_price'), 'listings', ['price'], unique=False)
    op.create_index(op.f('ix_listings_property_type'), 'listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_listings_rooms'), 'listings', ['rooms'], unique=False)
    op.create_index(op.f('ix_listings_scraped_at'), 'listings', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_listings_source'), 'listings', ['source'], unique=False)
    op.create_table('scraping_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_listings_found', sa.Integer(), nullable=False),
    sa.Column('new_listings_added', sa.Integer(), nullable=False),
    sa.Column('updated_listings', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('filters_used', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraping_source_status', 'scraping_sessions', ['source', 'status'], unique=False)
    op.create_index('idx_scraping_started_at', 'scraping_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_id'), 'scraping_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_source'), 'scraping_sessions', ['source'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_started_at'), 'scraping_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_status'), 'scraping_sessions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_subscription', 'users', ['subscription_type', 'subscription_expires_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_subscription_type'), 'users', ['subscription_type'], unique=False)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('min_rooms', sa.Integer(), nullable=True),
    sa.Column('max_rooms', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('min_area', sa.Integer(), nullable=True),
    sa.Column('max_area', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('last_notification_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_filter_city_price', 'filters', ['city', 'min_price', 'max_price'], unique=False)
    op.create_index('idx_filter_notifications', 'filters', ['notification_enabled', 'last_notification_sent'], unique=False)
    op.create_index('idx_filter_user_active', 'filters', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_filters_city'), 'filters', ['city'], unique=False)
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    op.create_index(op.f('ix_filters_is_active'), 'filters', ['is_active'], unique=False)
    op.create_index(op.f('ix_filters_max_price'), 'filters', ['max_price'], unique=False)
    op.create_index(op.f('ix_filters_property_type'), 'filters', ['property_type'], unique=False)
    op.create_index(op.f('ix_filters_user_id'), 'filters', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_pending', 'notifications', ['status', 'attempts', 'max_attempts'], unique=False)
    op.create_index('idx_notification_status_created', 'notifications', ['status', 'created_at'], unique=False)
    op.create_index('idx_notification_user_filter', 'notifications', ['user_id', 'filter_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_filter_id'), 'notifications', ['filter_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_listing_id'), 'notifications', ['listing_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_listing_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_filter_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_filter', table_name='notifications')
    op.drop_index('idx_notification_status_created', table_name='notifications')
    op.drop_index('idx_notification_pending', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_filters_user_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_property_type'), table_name='filters')
    op.drop_index(op.f('ix_filters_max_price'), table_name='filters')
    op.drop_index(op.f('ix_filters_is_active'), table_name='filters')
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_city'), table_name='filters')
    op.drop_index('idx_filter_user_active', table_name='filters')
    op.drop_index('idx_filter_notifications', table_name='filters')
    op.drop_index('idx_filter_city_price', table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_type'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_subscription', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scraping_sessions_status'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_started_at'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_source'), table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_id'), table_name='scraping_sessions')
    op.drop_index('idx_scraping_started_at', table_name='scraping_sessions')
    op.drop_index('idx_scraping_source_status', table_name='scraping_sessions')
    op.drop_table('scraping_sessions')
    op.drop_index(op.f('ix_listings_source'), table_name='listings')
    op.drop_index(op.f('ix_listings_scraped_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_rooms'), table_name='listings')
    op.drop_index(op.f('ix_listings_property_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_price'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_active'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_district'), table_name='listings')
    op.drop_index(op.f('ix_listings_city'), table_name='listings')
    op.drop_index(op.f('ix_listings_area'), table_name='listings')
    op.drop_index('idx_listing_source_active', table_name='listings')
    op.drop_index('idx_listing_scraped_at', table_name='listings')
    op.drop_index('idx_listing_rooms_area', table_name='listings')
    op.drop_index('idx_listing_coordinates', table_name='listings')
    op.drop_index('idx_listing_city_price', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
