"""add created_at field to listings table

Revision ID: d8063bfa6e97
Revises: ce901f74c668
Create Date: 2025-07-23 16:08:23.338987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8063bfa6e97'
down_revision: Union[str, None] = 'ce901f74c668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку как nullable
    op.add_column('listings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    
    # Обновляем все существующие записи, устанавливая created_at = scraped_at
    op.execute("UPDATE listings SET created_at = scraped_at WHERE created_at IS NULL")
    
    op.create_index(op.f('ix_listings_created_at'), 'listings', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_created_at'), table_name='listings')
    op.drop_column('listings', 'created_at')
    # ### end Alembic commands ###
