"""add_whatsapp_fields_to_users

Revision ID: da096da68aef
Revises: 3bbdf8a6923d
Create Date: 2025-07-31 11:11:04.024417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da096da68aef'
down_revision: Union[str, None] = '3bbdf8a6923d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('whatsapp_instance_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index('idx_user_messaging', 'users', ['telegram_chat_id', 'whatsapp_phone'], unique=False)
    op.create_index('idx_user_whatsapp_enabled', 'users', ['whatsapp_enabled', 'whatsapp_phone'], unique=False)
    op.create_index(op.f('ix_users_whatsapp_enabled'), 'users', ['whatsapp_enabled'], unique=False)
    op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp_phone'), table_name='users')
    op.drop_index(op.f('ix_users_whatsapp_enabled'), table_name='users')
    op.drop_index('idx_user_whatsapp_enabled', table_name='users')
    op.drop_index('idx_user_messaging', table_name='users')
    op.drop_column('users', 'whatsapp_enabled')
    op.drop_column('users', 'whatsapp_instance_id')
    op.drop_column('users', 'whatsapp_phone')
    # ### end Alembic commands ###
